### ISSUE TITLE
React wrappers

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core-elements#11]
Investigate if it’s possible to auto-generate React wrappers for Vaadin Components.

**Comment by jounik** [comment]
Apparently there’s `React.createClass` that should be used. Here’s an example of a jQuery widget wrapped as a React component: https://github.com/chenglou/react-chosen/blob/master/react-chosen.js

**Comment by jounik** [comment]
@tehapo, could you write any conclusions you got after spending some time with this?

**Comment by tehapo** [comment]
Unfortunately I didn't yet have much time for this after all. :disappointed: 

My only real finding on React + Vaadin Elements was the unsupported custom attribute we have defined in ```<vaadin-grid>```, which is the ```<col header-text="foobar" />```.

While React 0.14 introduced support for custom elements and attributes, it still does not support custom attributes on standard HTML elements.

**Comment by jouni** [comment]
Closing, as our current focus is purely on making awesome elements for Polymer and any frameworks that work out-of-the-box with Polymer and/or web components.
