### ISSUE TITLE
vaadin-combo-box not updating the drop down list correctly

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-core-elements#118]
Given this very simple combobox (version 1.3.3):
`<vaadin-combo-box id="cb"></vaadin-combo-box>`
Initializing it with:
`this.$.cb.items = ["Apple", "Banana"];`
(and it works correctly)
But if I then update the items list with:
`this.$.cb.items = ["Orange"];`
I obtain a dropdown list where the first item is 'Orange', but it's still present the second with 'Banana'.
In general the new list is 'copied over' the previous, without clearing it: if I have a list of 30 elements, and I set a new list of 10, the first 10 will be in the new list, and the other 20 the old, being always 30 elements.

**Comment by andreabioli** [comment]
I have to add one probably more important mis-behavior (probably due to new versions of components?):
If you create *today* a starter kit vaadin application (vaadin-elements-app) from the Polymer CLI (polymer init), you obtain an application where on the first page you can see just the (bad) behavior I just described.
So it's easy to reproduce: you should really give a look, because it looks like a major problem!
It's only in Chrome, but probably it's an important browser to support! :-)
Andrea

**Comment by Saulis** [comment]
Hi @andreabioli!

I'm going to close it as I'm pretty sure this is a duplicate item for https://github.com/vaadin/vaadin-combo-box/issues/426, which has been fixed in `v2.0.0-alpha1` – please give it a try.
