### ISSUE TITLE
NPM releases

### ISSUE THREAD

**Issue by moebiusmania** [vaadin/vaadin-core-elements#124]
hi, are you already planning or working on an NPM release of your Web Components collection?

**Comment by limonte** [comment]
All our components are released on npm: https://www.npmjs.com/~vaadin

On the other hand, Polymer by itself does not support npm currently. Fortunately, npm support is their main focus now. You can subscribe to https://github.com/Polymer/polymer/issues/326 to follow any updates on the subject.

We will align our components for npm right after the Polymer team come up with the official way to do that.

Thanks for using our components!
