### ISSUE TITLE
Add static code analysis to projects

### ISSUE THREAD

**Issue by wolfie** [vaadin/vaadin-core-elements#25]
We should bring in some static analysis and coding conventions to our projects.

Suggested tools:
- [JSHint](http://jshint.com/) for common JS errors.
- [JSCS](http://jscs.info/) for coding conventions.
- [polylint](https://github.com/PolymerLabs/polylint) for common errors in Polymer code.

Atom has plugins for JSHint, JSCS and polylint, but unfortunately JSCS is still missing the feature to lint JS code inside HTML documents (https://github.com/AtomLinter/linter-jscs/issues/110). Also the polylint plugin for Atom seems to be quite buggy.

Using JSCS from command-line does work with HTML documents via `--extract' flag:

```
$ jscs --extract vaadin-combo-box.html -p google .
...
One space required after "if" keyword at ./vaadin-combo-box.html :
   253 |
   254 |    _onArrowDown: function() {
   255 |      if(this.opened) {
----------------^
   256 |        this._focusedIndex = Math.min(this.$.selector.items.length - 1, this._focusedIndex + 1);
   257 |      } else {
...
```

Whether we're using these tools inside editor/IDE or not, we should still add these as part of our build process to catch errors at the latest on Travis build.

TODO:
- [x] [JSHint + JSCS for vaadin-combo-box](https://github.com/vaadin/vaadin-combo-box/pull/64)
- [ ] Polylint for vaadin-combo-box
- [ ] [JSHint + JSCS for vaadin-grid](https://github.com/vaadin/vaadin-grid/pull/286)
- [ ] Polylint for vaadin-grid

**Comment by tehapo** [comment]
Played around with Gulp tasks for linting JS code with JSHint and JSCS.
https://github.com/vaadin/vaadin-combo-box/commit/2c623f7c07ceb93d1a5c8d156678296a8e0a127b

**Comment by jounik** [comment]
https://github.com/vaadin/vaadin-combo-box/pull/64
