### ISSUE TITLE
Unify READMEs’ instuctions about npm permissions

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-core-elements#34]
Currently there’re differences about npm install across our elements:

- vaadin-grid’s README has both link to stackoverflow.com topic on resolving permission problems and a note about probable sudo requirement

- vaadin-combo-box and vaadin-icons READMEs neither mentions sudo nor permission problems resolution topic

To get those unified I suggest to:

1. Remove the `sudo` note from vaadin-grid README.

2. Copy the link about resolving permission problems from vaadin-grid’s README to every other element’s. Or remove it from vaadin-grid as well.

Using sudo should not be recommended. It results in setting root-only restricted permissions on some npm package and cache directories, that could introduce even harder maintenance problems. Generally, it’s not our job to instruct users about permissions on their systems. For ex., neither `polyserve` nor `web-component-tester` READMEs, nor even gulp getting started docs mentions `sudo`. If we still want to help our users to get over npm permission issues, we’d better instruct them to fix global installs, to make them working without `sudo`.

**Comment by jounik** [comment]
:+1: 

I actually have the task of creating a unified README template for all of our elements in my todo right now, so this comes in at a very appropriate time.

There’s actually a section this repos readme about developing the elements, which would be the place where any sudo related instructions should be: https://github.com/vaadin/vaadin-core-elements#development

Then we can just link to that section in our individual element readmes.

**Comment by jounik** [comment]
The https://github.com/vaadin/vaadin-core-elements#development instructions now include a note about the npm sudo issue.

**Comment by jounik** [comment]
Updated vaadin-grid readme to refer to the generic development instructions also.

**Comment by jounik** [comment]
I think this issue can be fixed as the instructions are now only in the vaadin-core-elements readme, and both the grid and combo-box refer to those instructions in their readmes. All future elements should do the same.
