### ISSUE TITLE
<vaadin-date-picker> remove the year toolbar

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-core-elements#36]
Remove the year toolbar and revise the whole date grid design accordingly.

**Comment by tuomasnironen** [comment]
[Date picker initial mockup](https://drive.google.com/open?id=0BzkWbWvgmkIxNGpMVlkxNUg0TlU) of the stretched layout with year toolbar removed.

**Comment by jounik** [comment]
Moved to https://github.com/vaadin/vaadin-date-picker/issues/97
