### ISSUE TITLE
<vaadin-upload> revised UI on desktop

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-core-elements#39]
Display "Drop files here..." text next to left aligned "Upload Files" button on desktop.

**Comment by tuomasnironen** [comment]
[\<vaadin-upload\> desktop designs](https://drive.google.com/open?id=0BzkWbWvgmkIxT3pRcEtKU094NzA)
* Empty upload
* Upload with files in the queue

**Comment by jounik** [comment]
Moved to vaadin-upload repo: https://github.com/vaadin/vaadin-upload/issues/38
