### ISSUE TITLE
Provide WebJar distribution

### ISSUE THREAD

**Issue by johndevs** [vaadin/vaadin-core-elements#50]
There are many out there who are building their client side apps with JVM based languages like Scala (Scala.js) or Groovy (grooscript). All of them are using Maven/Gradle for dependency management and WebJars (http://www.webjars.org) to pull int the client side libraries. 

We should also provide a WebJar with Vaadin core elements to allow people to build great client side apps with our elements with JVM languages as well.

**Comment by tomivirkki** [comment]
Bumped into this http://www.webjars.org/bower. Would it be an option to use vaadin-core-element trough Bower WebJars? Haven't tried it myself.

**Comment by manolo** [comment]
Already released, look for vaadin-core-elements at https://dl.bintray.com/webjars/maven/org/webjars/bower/
