### ISSUE TITLE
Context menu element [💰13]

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core-elements#53]
Draft for a possible new element, for creating context menus for any part of the UI.

#### Definition

(A lot of this is also defined in the Material design "Menus" specs: https://material.google.com/components/menus.html)

A context menu is **a list of options that depend on the context for which the menu is displayed**. It can be a hierarchical list, and it can contain disabled items and dividers. It is commonly displayed as an overlay on top of the other page content.

> ![screen shot 2016-06-08 at 11 46 36](https://cloud.githubusercontent.com/assets/66382/15888219/af612a96-2d6e-11e6-928d-481142759b8a.png)

A context menu usually contains less options than a regular menu, possibly only a relevant subset of actions from the full application menu for the given context. Otherwise the functionality is very similar.

A "context" can be pretty much anything, and the lowest level we can define technically is an HTML element (hierarchy). As this is intended to be a general purpose element, it is the application developer’s responsibility to provide the context dependent information for the menu.

#### Items 

The items are usually clickable/actionable, and perform some action that targets the context, but they can also be purely informative. Some items can also be toggles (on/off, checked/unchecked), although that is a less common use case for context menus (but common for application menus).

> ![screen shot 2016-06-08 at 13 17 44](https://cloud.githubusercontent.com/assets/66382/15891063/6cf305e6-2d7b-11e6-8dd0-acd1ab6d9aa4.png)

Visually the items are usually short one line strings, but can also contain icons or multiline text. The visual formatting of the items should be the responsibility of the developer, but a simple default representation is provided.

> ![screen shot 2016-06-08 at 13 24 16](https://cloud.githubusercontent.com/assets/66382/15891240/4fea40b2-2d7c-11e6-97e2-384ec47880b9.png)

#### Interaction

When a mouse is used for interaction, the context menu opens from the secondary mouse button or from ctrl+primary mouse button.

On touch devices, long press/touch will open it.

The user can navigate the menu using the keyboard arrow keys, and activate the items using the enter key.

The context menu should open relative to the mouse/touch coordinates (but always contained within the browser viewport). On small viewports, the context menu should open as an bottom/action sheet, and the coordinates are ignored.

> ![screen shot 2016-06-08 at 13 33 21](https://cloud.githubusercontent.com/assets/66382/15891524/9a3b6f8c-2d7d-11e6-9cb2-1c267848387a.png)

The context should also be programmatically openable, so the developer can provide an explicit button to open it (useful for touch devices for example, to help discovery). In this situation, it should also be possible to specify the target location for the context menu (where it should open on the screen, for example beneath the button that triggers the context menu).

> ![screen shot 2016-06-08 at 14 03 02](https://cloud.githubusercontent.com/assets/66382/15892322/c155a700-2d81-11e6-9726-c593053d60f9.png)

#### Other considerations

Specific places for a context menu:
- Grid cells (header, footer, body) and rows (selected or focused)

#### Implementation ideas

By default, the context menu applies to it’s parent element (to the `<body>` element in this example), and listens events on that element that will trigger the menu (context-click/right-click or long-press):

```html
<body>

<vaadin-context-menu>
  <vaadin-menu-item>Option 1</vaadin-menu-item>
  <vaadin-menu-item>Option 2</vaadin-menu-item>
  <vaadin-menu-item>Option 3</vaadin-menu-item>

  <vaadin-menu-item divider>Other options</vaadin-menu-item>

  <vaadin-menu-item toggle>
    <paper-item>
      <paper-item-body two-line>
        <div>Option 4</div>
        <div secondary>Another line for the option</div>
      </paper-item-body>
    </paper-item>
  </vaadin-menu-item>

  <vaadin-menu-item toggle>Option 5</vaadin-menu-item>
</vaadin-context-menu>

</body>
```

To target a specific element (hierarchy), use the "for" attribute. The "open" event could be a callback function that can provide the "context" object for the menu data binding.
- Question: what if the callback needs to perform an async operation to able to provide the context info?

```html
<paper-tabs id="my-tabs">
  <paper-tab>Tab 1</paper-tab>
  <paper-tab>Tab 2</paper-tab>
  <paper-tab>Tab 3</paper-tab>
</paper-tabs>

<vaadin-context-menu for="my-tabs" on-open="opened" on-item-click="itemClicked">
  <template is="dom-if" if="{{context.isTab}}">
    <vaadin-menu-item>Close Tab "[[context.tab.title]]"</vaadin-menu-item>
    <vaadin-menu-item>Close Other Tabs</vaadin-menu-item>
    <vaadin-menu-item divider></vaadin-menu-item>
  </template>
  <vaadin-menu-item>Open a New Tab</vaadin-menu-item>  
<vaadin-context-menu>
```

### Features for MVP

- Flat list of options (no hierarchy)
- Mouse and touch interaction (no keyboard support yet)
- Small viewport support (responsive)
- Context dependent items

**Comment by wolfie** [comment]
A nice release is needed at the end of the sprint.

**Comment by jouni** [comment]
Still missing:
- Mobile (small viewport + touch) support (vaadin/components-team-tasks#200)
- Context dependent items
- Final default styles and theme mixins/custom props
