### ISSUE TITLE
Split layout element [💰7]

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core-elements#55]
A basic split panel element, that allows the end user to divide an area in the UI to two sections with a certain ratio. The area can be divided either horizontally or vertically.
### Existing work

There’s already a ready made element for Polymer 0.5, and it’s probably fairly easy to port for 1.0

https://github.com/Polymer/core-splitter

We should package that neatly, so that the developer doesn’t have to provide any of the layout attributes.
### Features
- Vertical or horizontal "orientation"
- Only two "container" areas (limit the number of child elements to two)
- "Container" areas can define min and max sizes, which limits the movement of the splitter bar
  - If there are conflicting rules, we need to define some way of resolving them
#### Code example

``` html
<!-- Vertical means that the panels are stacked vertically, 
     so there the split is top/bottom -->
<vaadin-split-panel vertical>
  <div style="min-height: 120px;">Top</div>
  <div style="flex: 1;">Bottom</div>
</vaadin-split-panel>
```
#### Mockup

![screen shot 2016-06-08 at 16 16 10](https://cloud.githubusercontent.com/assets/66382/15895508/55ba592e-2d94-11e6-9ddb-14486ae65044.png)

The main `<vaadin-split-panel>` element would be a flex layout, and by default the contained elements be flexed equally to fill the whole element.

Only the first two child elements are renderer, others are ignored (removed/hidden?).
### Extra features
- Allow the splitter to be styled into a 1px divider, but still have a larger hit area
- Click the splitter to collapse/expand either side of the split

**Comment by platosha** [comment]
Repo: https://github.com/vaadin/vaadin-split-panel

*Status*

- [ ] First implementation
- [ ] Tests
- [ ] Documentation
- [ ] UX testing
- [ ] DX testing
- [ ] Beta review
- [ ] v1.0.0 release
