### ISSUE TITLE
vaadin-grid: updating while scrolling

### ISSUE THREAD

**Issue by ccschneidr** [vaadin/vaadin-core-elements#57]
Vaadin Grid looks great and fulfills many of our need for a data table. One issue I could not yet resolve is "flickering" while scrolling to new records. The actual flickering is not caused by the grid but by the elements shown, but the grid is the only thing that can help: when inserting something different than text (e.g. images) these elements might take a short time to load. On the other hand elements reused while scrolling probably animate to their new state when inserted at the other end. To avoid this kind of user-irritating effects I would like to increase the number of invisible rows / amount of invisible space when scrolling. Is this already possible? If no would it be easy to introduce? Or do you have another idea to allow data elements to initialize themselfes for some time before showing them to the user (at least for slow scrolling)?

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-grid#388
