### ISSUE TITLE
bug with data picker. close button not reappearing

### ISSUE THREAD

**Issue by joeblew99** [vaadin/vaadin-core-elements#61]
the close ("x") button appears when i open a datetime picker.
But when i try it a 2nd time, the "x" button does not appear.

This is happening on the demos on your web page.
I am on Chrome latest on OSX btw

**Comment by tomivirkki** [comment]
Hi @joeblew99

The "x" button is actually meant for clearing the date picker value and it's only visible if the component has a value.

So if you've clicked it prior to opening the dropdown for the second time, the component has no value and thus the button is not showing.
