### ISSUE TITLE
"Cannot select falsey values(0, "", false)"

### ISSUE THREAD

**Issue by chaithanyas-TDG** [vaadin/vaadin-core-elements#63]
Hello, I'm using `<vaadin-combo-box" component in Polymer in our application. When we're binding the values, there are falsey values like numeric zero(o), empty string(""). However, when user tries to select these values, Vaadin control doesn't allow to select in the first attempt. But, if selected again, that option is selected. This is bug IMO. Any option, regardless of its value should be selected in first attempt.

I think the issue is that the control doesn't allow falsey values in JavaScript and considers them as default values.

We've checked this by changing the values to other values than falsey and it works. However, we cannot change the values. Is there any configuration option in the control by which we can tell Vaadin to not consider these values as default value?

**Comment by Saulis** [comment]
This issue was moved to vaadin/vaadin-combo-box#315
