### ISSUE TITLE
Prototype an input element with Polymer 2 [🕔1d]

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-core-elements#71]
Use cases to implement:

1. A custom input based on the native input, which uses a native input value. Think of a generic text input, like `<paper-input>`.

2. A custom input based on the native input, which provides a different value from the input one. Think of a `<vaadin-date-picker>`, which formats a date in a human format in the input field, but gives an ISO-formatted date in the `value` property.

3. A custom input not based on the native one. Think of a `<paper-toggle-button>`.

**Comment by jouni** [comment]
This issue was moved to vaadin/components-team-tasks#214
