### ISSUE TITLE
snippet format issue in react integration section

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-core-elements#87]
Can be checked in [docs site](https://vaadin.com/docs/-/part/elements/integrations/integrations-react.html). It looks like:
<img width="786" alt="screen shot 2016-12-21 at 11 28 49" src="https://cloud.githubusercontent.com/assets/9820084/21392870/af703ed6-c770-11e6-97c5-0546c70c0b30.png">

**Comment by Saulis** [comment]
Thanks!

I've updated the snippet so that it will get fixed on the next update.
