### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by OracPrime** [vaadin/vaadin-core-elements#94]
Any plans to publish @types/vaadin-core-elements?   I'm just starting to evaluate this package for inclusion in a project which is mainly using typescript, and it seems a shame not to have the types for this.

Thanks

**Comment by manolo** [comment]
We don't have any plan right now, but we want to provide these files in the future.
Probably when polymer officially releases a tool for doing that.

In the meanwhile you could try out https://github.com/bsorrentino/generator-polymerts, I have not tried it yet but seems to do it's work for polymer 1.x elements

**Comment by OracPrime** [comment]
Ah, I'm using React.  Not quite sure whether the requirements are the same.

**Comment by manolo** [comment]
We will wait until a reliable tool for producing those definition files is released.

**Comment by basisbit** [comment]
any update on TypeScript support using current versions of vaadin? Any workarounds or example projects available anywhere?

**Comment by nickolay** [comment]
Looks like the updates happen in #186.
