### ISSUE TITLE
Getting started instructions with ZIP don't work

### ISSUE THREAD

**Issue by rjahn** [vaadin/vaadin-core-elements#96]
Followed: https://vaadin.com/docs/-/part/elements/elements-getting-started.html

Your release ZIP of core-elements doesn't contain dependencies!

If you offer ZIP releases, they should work!

**Comment by jouni** [comment]
Thanks for the report! We haven’t actually really supported the ZIP package in a while, so we should probably just remove the instructions for now.

But, it seems you at least would like that installation option, right? Or would you be okay with using Bower (or Yarn in the future) for installing our elements?

**Comment by rjahn** [comment]
It's always nice to use install-free variants, especially for simple tests.
Sure, node.js/npm and bower is an option.

But your official docs contains the ZIP option and you release zip archives? If you remove both, it's clear.

I guess there are more ZIP users out there, because it's easy and fast without installation of additional software.

**Comment by jouni** [comment]
I agree that the zip package is a great option to have. We just haven’t really put a lot of focus on that, as it hasn’t seemed like a priority.

There was actually an open issue for this not too long ago: #41. We could probably reopen that also.

**Comment by jouni** [comment]
I uploaded the zip package for the latest 1.5.0 release, so you can at least try with that.

**Comment by rjahn** [comment]
Your update works! Thanks.
