### ISSUE TITLE
Polymer 2 support?

### ISSUE THREAD

**Issue by andersforsell** [vaadin/vaadin-core-elements#97]
Hi, 

Thanks for the nice elements!

I'm wondering if I can use your elements with Polymer 2 (currently at 2.0.0-rc.1) ?

If not, when do you plan to support it?

Thanks again!

**Comment by jouni** [comment]
We are currently finishing up vaadin-grid 2.0. After that, we will do hybrid versions of all of the existing elements (grid, combo-box, date-picker, upload, context-menu, split-layout).

Split-layout already has Polymer 2 support: https://github.com/vaadin/vaadin-split-layout/releases/tag/v1.1.0-alpha1

**Comment by jouni** [comment]
Closing this issue. You can check the status of Polymer 2 compatibility from the [readme](https://github.com/vaadin/vaadin-core-elements/blob/master/README.md), which has links to all the relevant individual issues for each element.
